version: '3'

services:
    
  annotrieve-mongo:
    image: mongo:7.0
    container_name: "${DB_HOST}"
    env_file:
      - .env
    restart: always
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - /data/annotrieve/mongo:/data/db
    ports:
      - "27030:27017"
    networks:
      - monstre

  annotrieve-nginx:
    image: gitlab.linux.crg.es:5005/monstre/annotrieve/annotrieve-nginx
    restart: always
    environment:
      - API_PORT=80
      - API_HOST=annotrieve-server
      - BASE_PATH=${BASE_PATH}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.annotrieve-nginx.rule=(Host(`genome.crg.es`) || Host(`genome.crg.cat`) || Host(`genome.crg.eu`)) && PathPrefix(`/annotrieve`)"
      - "traefik.http.routers.annotrieve-nginx.tls=true"
      - "traefik.http.routers.annotrieve-nginx.entrypoints=web_https"
      - "traefik.http.services.annotrieve-nginx.loadBalancer.server.port=80"
    networks:
      - monstre

  annotrieve-server:
    image: gitlab.linux.crg.es:5005/monstre/annotrieve/annotrieve-server
    restart: always
    volumes:
      - ./server:/server
      - /data/annotrieve/annotations:${LOCAL_ANNOTATIONS_DIR}
      - /data/annotrieve/zip:${ZIP_FOLDER_PATH}
    env_file:
      - .env
    depends_on:
      - annotrieve-redis
    networks:
      - monstre

  annotrieve-celery:
    image: gitlab.linux.crg.es:5005/monstre/annotrieve/annotrieve-server
    command: celery --app app.celery_app worker --loglevel=info --autoscale=1,1 --max-tasks-per-child=1
    restart: always
    volumes:
      - ./server:/server
      - /data/annotrieve/annotations:${LOCAL_ANNOTATIONS_DIR}
      - /data/annotrieve/zip:${ZIP_FOLDER_PATH}
    env_file:
      - .env
    depends_on:
      - annotrieve-server
      - annotrieve-mongo
      - annotrieve-redis
    networks:
      - monstre

  annotrieve-celery-beat:
    image: gitlab.linux.crg.es:5005/monstre/annotrieve/annotrieve-server
    command: celery --app app.celery_app beat --loglevel=info
    restart: always
    volumes:
      - ./server:/server
      - /data/annotrieve/annotations:${LOCAL_ANNOTATIONS_DIR}
      - /data/annotrieve/zip:${ZIP_FOLDER_PATH}
    env_file:
      - .env
    depends_on:
      - annotrieve-server
      - annotrieve-mongo
      - annotrieve-redis
    networks:
      - monstre

  annotrieve-redis:
    image: "redis:alpine"
    expose:
      - "6378"
    networks:
      - monstre
networks:
  monstre:
    external:
      name: monstre
