services:

  annotrieve-nginx:
    image: gitlab.hpc.crg.es:5005/monstre/annotrieve/annotrieve-nginx
    restart: always
    environment:
      - BASE_PATH=${BASE_PATH}
    volumes:
      - ${ANNOTATIONS_DATA_PATH}:/data/annotrieve/files:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.annotrieve-nginx.rule=(Host(`genome.crg.es`) || Host(`genome.crg.cat`) || Host(`genome.crg.eu`)) && PathPrefix(`/annotrieve`)"
      - "traefik.http.routers.annotrieve-nginx.tls=true"
      - "traefik.http.routers.annotrieve-nginx.entrypoints=web_https"
      - "traefik.http.services.annotrieve-nginx.loadBalancer.server.port=80"
    networks:
      - monstre

  annotrieve-mongodb:
    image: mongo:8.0
    container_name: "${DB_HOST}"
    env_file:
      - .env
    restart: always
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ${MONGODB_DATA_PATH}:/data/db
    ports:
      - "${MONGODB_PORT:-27030}:27017"
    networks:
      - monstre

  annotrieve-redis:
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"
    networks:
      - monstre

  annotrieve-fastapi:
    image: gitlab.hpc.crg.es:5005/monstre/annotrieve/annotrieve-fastapi
    container_name: annotrieve-fastapi
    restart: always
    # Production uses Gunicorn (CMD in Dockerfile), override only if needed
    volumes:
      - ${ANNOTATIONS_DATA_PATH}:${LOCAL_ANNOTATIONS_DIR}
    env_file:
      - .env
    depends_on:
      - annotrieve-redis
      - annotrieve-mongodb
    expose:
      - "5000"
    networks:
      - monstre
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  annotrieve-fastapi-celery:
    image: gitlab.hpc.crg.es:5005/monstre/annotrieve/annotrieve-fastapi
    restart: always
    command: celery --app celery_app.celery_worker.app worker --loglevel=info --autoscale=2,1 --max-tasks-per-child=1
    volumes:
      - ${ANNOTATIONS_DATA_PATH}:${LOCAL_ANNOTATIONS_DIR}
    env_file:
      - .env
    depends_on:
      - annotrieve-fastapi
      - annotrieve-mongodb
      - annotrieve-redis
    networks:
      - monstre

  annotrieve-fastapi-celery-beat:
    image: gitlab.hpc.crg.es:5005/monstre/annotrieve/annotrieve-fastapi
    restart: always
    command: celery --app celery_app.celery_worker.app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - ${ANNOTATIONS_DATA_PATH}:${LOCAL_ANNOTATIONS_DIR}
    env_file:
      - .env
    depends_on:
      - annotrieve-fastapi
      - annotrieve-mongodb
      - annotrieve-redis
    networks:
      - monstre

networks:
  monstre:
    external:
      name: monstre

volumes:
  mongodb-data:
  annotations-data:

