ncbi-genbank:
  tsv_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz
  label: NCBI GenBank
  chr_alias_key: genbank_accession
ensembl-rapid-release:
  tsv_url: https://ftp.ensembl.org/pub/rapid-release/gff3/homo_sapiens/Homo_sapiens.GRCh38.109.gff3.gz
  label: Ensembl Rapid Release
  chr_alias_key: chr_name
ncbi-refseq:
  tsv_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz
  label: NCBI RefSeq
  chr_alias_key: refseq_accession
